php:
  preset: laravel
  version: 8
  tab-width: 2
  use-tabs: false
  finder:
    exclude:
      - 'vendor'
    name: '*.php'
js:
  tab-width: 2
  use-tabs: false
  semicolons: false
  finder:
    exclude:
      - 'node_modules'
